[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build phase needed for Python'"]

[start]
cmd = "cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT run:app" 