[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.build]
env = { FLASK_APP = "run:app" }
cmds = ["python -m flask db upgrade"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT run:app" 