services:
  - type: web
    name: wega-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
    autoDeploy: true
    
databases:
  - name: wega-backend-db
    plan: free 