services:
  - type: web
    name: wega-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      echo "🔧 Database upgrade..."
      flask db upgrade || echo "Database upgrade completed or not needed"
      echo "🌱 Starting database seeding..."
      cd /opt/render/project/src
      python3 scripts/reseed_with_cloudinary.py || echo "Seeding completed or failed - check logs"
      echo "✅ Build and seeding complete!"
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: wega-backend-db
          property: connectionString
      - key: JWT_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
    autoDeploy: true
    
databases:
  - name: wega-backend-db
    plan: free 